### ISSUE TITLE
Editing and deleting does not work

### ISSUE THREAD

**Issue by NoBody92** [Placenote/PlacenoteSDK-ARNotes#2]
Is it possible that there a bug in editing and deleting notes when you load an existing map. When I load an exiting map I can't shortly something, but it's getting saved permantly. After some seconds the new notes disapear or all changes on the exiting notes are gone.

**Comment by navganti** [comment]
Hi @NoBody92 - apologies for the delayed response. Good catch! I've fixed this in the latest commit. Please pull the latest, and you should be good to go :)

**Comment by navganti** [comment]
@NoBody92 Also, feel free to join our dev community (www.placenote.com/slack) for faster answers! We're far more active over there 🙂
